"""Generated by tools/mmq_deployment_bundle.py. Do not edit directly.

Device row-task tiles and split-contraction slice counts of the exact public
records, keyed by `(operation, quant_type, rows, out_features, in_features)`.
A missing key means the record runs as one launch over the route bank.
"""

# KernelFamily member names, spelled exactly as the generated host table.
ROW_TASK_TILES: dict[tuple[str, int, int, int, int], int] = {
    ("GroupedBackward", 42, 20480, 2560, 640): 128,
    ("GroupedBackward", 42, 81920, 2560, 640): 256,
    ("GroupedBackward", 42, 327680, 2560, 640): 256,
    ("GroupedBackwardPair", 42, 20480, 640, 2560): 128,
    ("GroupedBackwardPair", 42, 81920, 640, 2560): 128,
    ("GroupedBackwardPair", 42, 327680, 640, 2560): 256,
    ("GroupedForwardPair", 11, 16384, 512, 2048): 64,
    ("GroupedForwardPair", 11, 65536, 512, 2048): 64,
    ("GroupedForwardPair", 11, 262144, 512, 2048): 64,
    ("GroupedForwardPair", 22, 16384, 512, 2048): 64,
    ("GroupedForwardPair", 22, 65536, 512, 2048): 64,
    ("GroupedForwardPair", 22, 262144, 512, 2048): 64,
}

SPLIT_SLICES: dict[tuple[str, int, int, int, int], int] = {
    ("OrdinaryBackward", 13, 64, 248320, 2560): 4,
    ("OrdinaryBackward", 13, 128, 248320, 2560): 8,
    ("OrdinaryBackward", 13, 256, 248320, 2560): 32,
}
