"""Content digests for generated artifacts and provenance evidence.

Kernel identity is owned by :mod:`tools.ggtensile.identity`. The values here
describe generated bytes only. They are never selection, naming, or dispatch
inputs.
"""

import hashlib


def sha256_hex(data: bytes) -> str:
    """Return the SHA-256 hex digest of raw content bytes."""
    return hashlib.sha256(data).hexdigest()
