import argparse
import subprocess
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "csrc/vendor/llama_cpp"


def _extract_region(text: str, marker: str, next_marker: str) -> str:
    start = text.index(marker)
    line_start = text.rfind("\n", 0, start) + 1
    previous_line_start = text.rfind("\n", 0, line_start - 1) + 1
    if text[previous_line_start:line_start].lstrip().startswith("template"):
        start = previous_line_start
    else:
        start = line_start
    end = text.index(next_marker, start)
    end = text.rfind("\n", 0, end) + 1
    previous = text.rfind("\n", 0, end - 1) + 1
    if text[previous:end].lstrip().startswith("template"):
        end = previous
    return text[start:end].rstrip() + "\n"


def _current_commit(root: Path) -> str:
    return subprocess.run(
        ["git", "-C", str(root), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _write_generated(path: Path, commit: str, content: str) -> None:
    path.write_text(
        "// Generated by tools/generate_vendor.py. Do not edit directly.\n"
        f"// llama.cpp commit: {commit}\n\n" + content
    )


def generate(root: Path) -> None:
    commit = _current_commit(root)
    source = root / "ggml/src"
    OUT.mkdir(parents=True, exist_ok=True)

    load_text = (source / "ggml-cuda/mmq-load-tiles.cuh").read_text()
    load_parts = [
        _extract_region(
            load_text, "ggml_cuda_mmq_load_tiles_q3_K(", "unpack_scales_q45_K("
        ),
        _extract_region(
            load_text, "unpack_scales_q45_K(", "ggml_cuda_mmq_load_tiles_q4_K("
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q4_K(",
            "ggml_cuda_mmq_load_tiles_q5_K(",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q5_K(",
            "ggml_cuda_mmq_load_tiles_q6_K(",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q6_K(",
            "// ---------------------------------------------------------------------------------------------",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_iq2_s(",
            "ggml_cuda_mmq_load_tiles_iq3_xxs(",
        ),
    ]
    _write_generated(
        OUT / "mmq-load-targets.cuh",
        commit,
        "#pragma once\n\n// Selectively vendored target-format MMQ tile loaders.\n\n"
        + "\n".join(load_parts),
    )

    dot_text = (source / "ggml-cuda/mmq-vec-dot.cuh").read_text()
    dot_parts = [
        _extract_region(
            dot_text,
            "ggml_cuda_mmq_vec_dot_q8_1_q8_1_mma(",
            "// Used for NVFP4, Q3_K, IQ2_S, and IQ2_XS",
        ),
        _extract_region(
            dot_text,
            "ggml_cuda_mmq_vec_dot_q8_0_16_q8_1_mma(",
            "ggml_cuda_mmq_vec_dot_q2_K_q8_1_dp4a(",
        ),
        _extract_region(
            dot_text,
            "ggml_cuda_mmq_vec_dot_q6_K_q8_1_mma(",
            "// ---------------------------------------------------------------------------------------------",
        ),
    ]
    _write_generated(
        OUT / "mmq-vec-dot-targets.cuh",
        commit,
        "#pragma once\n\nusing namespace ggml_cuda_mma;\n\n"
        "// Selectively vendored target-format int8-WMMA dot products.\n\n"
        + "\n".join(dot_parts),
    )

    common_text = (source / "ggml-common.h").read_text()
    table_start = common_text.index("GGML_TABLE_BEGIN(uint64_t, iq2s_grid, 1024)")
    table_end_marker = "GGML_TABLE_END()"
    table_end = common_text.index(table_end_marker, table_start) + len(table_end_marker)
    table = common_text[table_start:table_end]
    table = table.replace(
        "GGML_TABLE_BEGIN(uint64_t, iq2s_grid, 1024)",
        "static const __device__ uint64_t iq2s_grid[1024] = {",
    ).replace(table_end_marker, "};")
    _write_generated(
        OUT / "iq2_s_grid.cuh",
        commit,
        "#pragma once\n\n// IQ2_S grid codebook from llama.cpp.\n" + table + "\n",
    )

    _write_generated(
        OUT / "mma.cuh",
        commit,
        (source / "ggml-cuda/mma.cuh").read_text(),
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--llama-cpp", type=Path, default=Path.home() / "llama.cpp")
    arguments = parser.parse_args()
    generate(arguments.llama_cpp.resolve())
