import argparse
import subprocess
from pathlib import Path
from urllib.parse import urlparse

OUT = Path(__file__).resolve().parents[1] / "csrc/vendor/llama_cpp"
PROVENANCE = OUT / "PROVENANCE.md"
PROVENANCE_START = "<!-- generate_vendor:begin -->"
PROVENANCE_END = "<!-- generate_vendor:end -->"
CANONICAL_REPOSITORY = ("github.com", "ggml-org/llama.cpp")
GENERATED_FILES = (
    "iq2_s_grid.cuh",
    "iq2_xxs_grid.cuh",
    "mma.cuh",
    "mmq-load-targets.cuh",
    "mmq-vec-dot-q2-k-rolled.cuh",
    "mmq-vec-dot-targets.cuh",
)

Q2_K_UNROLL = 4


def _extract_region(text: str, marker: str, next_marker: str) -> str:
    start = text.index(marker)
    line_start = text.rfind("\n", 0, start) + 1
    previous_line_start = text.rfind("\n", 0, line_start - 1) + 1
    if text[previous_line_start:line_start].lstrip().startswith("template"):
        start = previous_line_start
    else:
        start = line_start
    end = text.index(next_marker, start)
    end = text.rfind("\n", 0, end) + 1
    previous = text.rfind("\n", 0, end - 1) + 1
    if text[previous:end].lstrip().startswith("template"):
        end = previous
    return text[start:end].rstrip() + "\n"


def _git(root: Path, *arguments: str) -> str:
    return subprocess.run(
        ["git", "-C", str(root), *arguments],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _repository_from_url(value: str) -> tuple[str, str] | None:
    value = value.strip().rstrip("/")
    if "://" in value:
        parsed = urlparse(value)
        host = parsed.hostname
        path = parsed.path
    elif value.startswith("git@") and ":" in value:
        host, path = value.removeprefix("git@").split(":", 1)
    else:
        return None
    path = path.strip("/")
    path = path.removesuffix(".git")
    if not host or not path:
        return None
    return host.lower(), path.lower()


def _canonical_master_ref(root: Path) -> str:
    refs = []
    for remote in _git(root, "remote").splitlines():
        urls = _git(root, "remote", "get-url", "--all", remote).splitlines()
        if not any(_repository_from_url(url) == CANONICAL_REPOSITORY for url in urls):
            continue
        ref = f"refs/remotes/{remote}/master"
        exists = (
            subprocess.run(
                ["git", "-C", str(root), "show-ref", "--verify", "--quiet", ref],
                check=False,
            ).returncode
            == 0
        )
        if exists:
            refs.append(ref)
    if not refs:
        raise RuntimeError(
            "no local master tracking ref for https://github.com/ggml-org/llama.cpp"
        )
    for candidate in refs:
        if all(
            other == candidate
            or subprocess.run(
                [
                    "git",
                    "-C",
                    str(root),
                    "merge-base",
                    "--is-ancestor",
                    other,
                    candidate,
                ],
                check=False,
            ).returncode
            == 0
            for other in refs
        ):
            return candidate
    raise RuntimeError("canonical llama.cpp master tracking refs disagree")


def _closest_canonical_commit(root: Path) -> str:
    return _git(root, "merge-base", "HEAD", _canonical_master_ref(root))


def _write_generated(path: Path, content: str) -> None:
    generated = (
        "// Generated by tools/generate_vendor.py. Do not edit directly.\n\n" + content
    )
    if not path.is_file() or path.read_text() != generated:
        path.write_text(generated)


def _write_provenance(commit: str) -> None:
    text = PROVENANCE.read_text()
    start = text.index(PROVENANCE_START) + len(PROVENANCE_START)
    end = text.index(PROVENANCE_END, start)
    generated = (
        "\n"
        "Canonical repository: <https://github.com/ggml-org/llama.cpp>\n\n"
        f"Closest ancestor on `master`: `{commit}`\n\n"
        "Generated files:\n\n" + "".join(f"- `{name}`\n" for name in GENERATED_FILES)
    )
    updated = text[:start] + generated + text[end:]
    if updated != text:
        PROVENANCE.write_text(updated)


def generate(root: Path) -> None:
    commit = _closest_canonical_commit(root)
    source = root / "ggml/src"
    OUT.mkdir(parents=True, exist_ok=True)

    load_text = (source / "ggml-cuda/mmq-load-tiles.cuh").read_text()
    load_parts = [
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q8_0(",
            "ggml_cuda_mmq_load_tiles_q2_K(",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q2_K(",
            "ggml_cuda_mmq_load_tiles_q3_K(",
        ),
        _extract_region(
            load_text, "ggml_cuda_mmq_load_tiles_q3_K(", "unpack_scales_q45_K("
        ),
        _extract_region(
            load_text, "unpack_scales_q45_K(", "ggml_cuda_mmq_load_tiles_q4_K("
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q4_K(",
            "ggml_cuda_mmq_load_tiles_q5_K(",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q5_K(",
            "ggml_cuda_mmq_load_tiles_q6_K(",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_q6_K(",
            "// ---------------------------------------------------------------------------------------------",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_iq2_xxs(",
            "ggml_cuda_mmq_load_tiles_iq2_xs(",
        ),
        _extract_region(
            load_text,
            "ggml_cuda_mmq_load_tiles_iq2_s(",
            "ggml_cuda_mmq_load_tiles_iq3_xxs(",
        ),
    ]
    _write_generated(
        OUT / "mmq-load-targets.cuh",
        "#pragma once\n\n// Selectively vendored target-format MMQ tile loaders.\n\n"
        + "\n".join(load_parts),
    )

    dot_text = (source / "ggml-cuda/mmq-vec-dot.cuh").read_text()
    q2_dot = _extract_region(
        dot_text,
        "ggml_cuda_mmq_vec_dot_q2_K_q8_1_mma(",
        "ggml_cuda_mmq_vec_dot_q3_K_q8_1_dp4a(",
    )
    q2_name = "ggml_cuda_mmq_vec_dot_q2_K_q8_1_mma("
    if q2_name not in q2_dot:
        raise ValueError("Q2_K MMQ function name changed upstream")
    q2_rolled_dot = q2_dot.replace(
        q2_name,
        "ggml_cuda_mmq_vec_dot_q2_K_q8_1_mma_rolled(",
        1,
    )
    q2_k_loop = "    for (int k01 = 0; k01 < MMQ_TILE_NE_K; k01 += 4) {"
    if q2_k_loop not in q2_rolled_dot:
        raise ValueError("Q2_K MMQ scale loop changed upstream")
    q2_rolled_dot = q2_rolled_dot.replace(
        q2_k_loop, f"#pragma unroll {Q2_K_UNROLL}\n" + q2_k_loop, 1
    )
    dot_parts = [
        _extract_region(
            dot_text,
            "ggml_cuda_mmq_vec_dot_q8_0_q8_1_mma(",
            "ggml_cuda_mmq_vec_dot_q8_1_q8_1_dp4a(",
        ),
        _extract_region(
            dot_text,
            "ggml_cuda_mmq_vec_dot_q8_1_q8_1_mma(",
            "// Used for NVFP4, Q3_K, IQ2_S, and IQ2_XS",
        ),
        _extract_region(
            dot_text,
            "ggml_cuda_mmq_vec_dot_q8_0_16_q8_1_mma(",
            "ggml_cuda_mmq_vec_dot_q2_K_q8_1_dp4a(",
        ),
        q2_dot,
        _extract_region(
            dot_text,
            "ggml_cuda_mmq_vec_dot_q6_K_q8_1_mma(",
            "// ---------------------------------------------------------------------------------------------",
        ),
    ]
    _write_generated(
        OUT / "mmq-vec-dot-targets.cuh",
        "#pragma once\n\nusing namespace ggml_cuda_mma;\n\n"
        "// Selectively vendored target-format int8-WMMA dot products.\n\n"
        + "\n".join(dot_parts),
    )
    _write_generated(
        OUT / "mmq-vec-dot-q2-k-rolled.cuh",
        "#pragma once\n\nusing namespace ggml_cuda_mma;\n\n"
        "// DeepSeek gfx1151 Q2_K specialization with bounded compiler unrolling.\n\n"
        + q2_rolled_dot,
    )
    common_text = (source / "ggml-common.h").read_text()
    table_start = common_text.index("GGML_TABLE_BEGIN(uint64_t, iq2s_grid, 1024)")
    table_end_marker = "GGML_TABLE_END()"
    table_end = common_text.index(table_end_marker, table_start) + len(table_end_marker)
    table = common_text[table_start:table_end]
    table = table.replace(
        "GGML_TABLE_BEGIN(uint64_t, iq2s_grid, 1024)",
        "static const __device__ uint64_t iq2s_grid[1024] = {",
    ).replace(table_end_marker, "};")
    _write_generated(
        OUT / "iq2_s_grid.cuh",
        "#pragma once\n\n// IQ2_S grid codebook from llama.cpp.\n" + table + "\n",
    )

    table_start = common_text.index("GGML_TABLE_BEGIN(uint64_t, iq2xxs_grid, 256)")
    table_end = common_text.index(table_end_marker, table_start) + len(table_end_marker)
    table = common_text[table_start:table_end]
    table = table.replace(
        "GGML_TABLE_BEGIN(uint64_t, iq2xxs_grid, 256)",
        "static const __device__ uint64_t iq2xxs_grid[256] = {",
    ).replace(table_end_marker, "};")
    _write_generated(
        OUT / "iq2_xxs_grid.cuh",
        "#pragma once\n\n// IQ2_XXS grid codebook from llama.cpp.\n" + table + "\n",
    )

    _write_generated(
        OUT / "mma.cuh",
        (source / "ggml-cuda/mma.cuh").read_text(),
    )
    _write_provenance(commit)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--llama-cpp", type=Path, default=Path.home() / "llama.cpp")
    arguments = parser.parse_args()
    generate(arguments.llama_cpp.resolve())
