"""Typed kernel inventory and generated host records for the MMQ bundle."""

from dataclasses import dataclass
from pathlib import Path

from tools.ggtensile.campaign import load_catalog
from tools.ggtensile.family_registry import (
    family_for_instance,
    instance_name,
    launch_for_instance,
    problem_size_for_instance,
    writer_for_instance,
)
from tools.ggtensile.identity import KernelFamily
from tools.ggtensile.kernel_instance import KernelInstance
from tools.ggtensile.toolchain import Toolchain
from tools.mmq_bundle_wrapper_source import (
    ForwardConfig,
    ForwardKind,
    QuantType,
)

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "tools/ggtensile/configs"


@dataclass(frozen=True)
class BundleKernel:
    cpp_id: str
    symbol: str
    instance: KernelInstance | None
    hip_config: ForwardConfig | None = None

    @property
    def operation(self) -> str | None:
        return (
            family_for_instance(self.instance).value
            if self.instance is not None
            else None
        )


def _hip_kernels() -> list[BundleKernel]:
    values = (
        (
            "QuantizeQ81F32D4",
            "quantize_bf16_q8_1_f32_d4",
            QuantType.Q8_0,
        ),
        (
            "QuantizeQ81F16D4S4",
            "quantize_bf16_q8_1_f16_d4s4",
            QuantType.Q4_K,
        ),
        (
            "QuantizeQ81F16D2S6",
            "quantize_bf16_q8_1_f16_d2s6",
            QuantType.Q2_K,
        ),
        (
            "GroupedRowTaskSetup",
            "grouped_row_task_setup",
            None,
        ),
    )
    return [
        BundleKernel(
            name,
            symbol,
            None,
            ForwardConfig(
                kind=ForwardKind.QUANTIZE if quant else ForwardKind.ROW_TASK_SETUP,
                quant_type=quant,
            ),
        )
        for name, symbol, quant in values
    ]


def kernels() -> tuple[BundleKernel, ...]:
    result = _hip_kernels()
    for path in sorted(CONFIG.glob("mmq_*_catalog.json")):
        catalog = load_catalog(path)
        for entry in catalog.entries:
            instance = entry.instance
            result.append(
                BundleKernel(
                    f"Kernel{len(result):03d}",
                    instance_name(instance),
                    instance,
                )
            )
    symbols = [item.symbol for item in result]
    if len(symbols) != len(set(symbols)):
        raise ValueError("deployment bundle contains duplicate symbols")
    return tuple(result)


def writer_for(kernel: BundleKernel, toolchain: Toolchain):
    if kernel.instance is None:
        raise TypeError("HIP support artifacts do not have a GGTensile writer")
    return writer_for_instance(kernel.instance, toolchain)


def _record(kernel: BundleKernel, kernel_index: int) -> tuple[int, ...] | None:
    instance = kernel.instance
    if instance is None:
        return None
    problem = problem_size_for_instance(instance)
    quant_name = instance.problem_type.quant_data_type
    launch = launch_for_instance(instance)
    return (
        list(KernelFamily).index(family_for_instance(instance)),
        QuantType[quant_name].value,
        problem.m,
        problem.n,
        problem.k,
        kernel_index,
        *launch.grid,
        *launch.work_group,
        launch.static_group_segment_bytes,
        int(launch.ownership == "DeviceRowTasks"),
        launch.row_task_rows or 0,
        launch.row_task_capacity or 0,
        launch.route_split_factor,
    )


def header_text(items: tuple[BundleKernel, ...]) -> str:
    symbols = "\n".join(f'    "{item.symbol}",' for item in items)
    records = [
        record
        for index, item in enumerate(items)
        if (record := _record(item, index)) is not None
    ]
    rows = "\n".join("    {" + ", ".join(map(str, record)) + "}," for record in records)
    indices = {item.cpp_id: index for index, item in enumerate(items)}
    operation_constants = "\n".join(
        f"inline constexpr int k{family.value} = {index};"
        for index, family in enumerate(KernelFamily)
    )
    quant_constants = "\n".join(
        f"inline constexpr int kQuant{quant.name} = {quant.value};"
        for quant in QuantType
    )
    return f"""// Generated by tools/mmq_deployment_bundle.py. Do not edit directly.
#pragma once
#include <array>
#include <cstdint>
namespace torch_ggml_ops::mmq_bundle {{
using MMQKernelIndex = std::uint16_t;
{operation_constants}
{quant_constants}
inline constexpr MMQKernelIndex kQuantizeQ81F32D4 = {indices["QuantizeQ81F32D4"]};
inline constexpr MMQKernelIndex kQuantizeQ81F16D4S4 = {indices["QuantizeQ81F16D4S4"]};
inline constexpr MMQKernelIndex kQuantizeQ81F16D2S6 = {indices["QuantizeQ81F16D2S6"]};
inline constexpr MMQKernelIndex kGroupedRowTaskSetup = {indices["GroupedRowTaskSetup"]};
inline constexpr std::array<const char *, {len(items)}> kMMQKernelSymbols{{{{
{symbols}
}}}};
inline constexpr const char * mmq_kernel_symbol(MMQKernelIndex index) {{
    return kMMQKernelSymbols[index];
}}
struct MMQDeploymentRecord {{
    int operation;
    int quant_type;
    int m;
    int n;
    int k;
    MMQKernelIndex kernel;
    unsigned int grid_x;
    unsigned int grid_y;
    unsigned int grid_z;
    unsigned int block_x;
    unsigned int block_y;
    unsigned int block_z;
    unsigned int shared_memory;
    int ownership;
    int row_task_rows;
    int row_task_capacity;
    int route_split_factor;
}};
inline constexpr std::array<MMQDeploymentRecord, {len(records)}> kMMQDeployments{{{{
{rows}
}}}};
}} // namespace torch_ggml_ops::mmq_bundle
"""
