"""Render the concrete C++ entry points compiled into the gfx1151 MMQ bundle."""

from dataclasses import dataclass
from enum import Enum, IntEnum


class QuantType(IntEnum):
    Q8_0 = 8
    Q2_K = 10
    Q3_K = 11
    Q4_K = 12
    Q5_K = 13
    Q6_K = 14
    IQ2_XXS = 16
    IQ2_S = 22


class ForwardKind(str, Enum):
    QUANTIZE = "quantize"
    DENSE = "dense"
    GROUPED_SERIAL = "grouped_serial"
    GROUPED_ROW_TASK = "grouped_row_task"
    FIXED_GROUPED = "fixed_grouped"
    ROW_TASK_SETUP = "row_task_setup"


class GroupedBackwardKind(str, Enum):
    GENERIC_SINGLE = "generic_single"
    GENERIC_PAIR = "generic_pair"
    Q4_SINGLE_M64 = "q4_single_m64"
    Q4_SINGLE_M128 = "q4_single_m128"
    Q3_PAIR_M64 = "q3_pair_m64"
    Q3_PAIR_M128 = "q3_pair_m128"
    Q5_SINGLE_M64 = "q5_single_m64"
    IQ2_S_SINGLE_M64 = "iq2_s_single_m64"
    IQ2_S_SINGLE_M128 = "iq2_s_single_m128"
    IQ2_S_PAIR_M64 = "iq2_s_pair_m64"
    IQ2_S_PAIR_M128 = "iq2_s_pair_m128"
    Q4_ROW_TASK = "q4_row_task"
    Q5_ROW_TASK = "q5_row_task"
    IQ2_S_ROW_TASK = "iq2_s_row_task"
    FIXED_Q8_0_GENERIC = "fixed_q8_0_generic"
    Q2_K_SINGLE_M64_U1 = "q2_k_single_m64_u1"
    Q2_K_SINGLE_M128_U1 = "q2_k_single_m128_u1"
    IQ2_XXS_PAIR_M64 = "iq2_xxs_pair_m64"
    Q2_K_SINGLE_M128_U2 = "q2_k_single_m128_u2"
    FIXED_Q8_0_M256 = "fixed_q8_0_m256"
    TUNED_DEEPSEEK_PAIR = "tuned_deepseek_pair"
    TUNED_FIXED_Q8_0 = "tuned_fixed_q8_0"


@dataclass(frozen=True)
class ForwardConfig:
    kind: ForwardKind
    quant_type: QuantType | None = None
    j: int = 0
    nrows_weight: int = 0
    blocks_per_weight_row: int = 0
    groups: int = 0
    fallback: bool = False
    rolled_q2: bool = False
    mixed_j32_tails: bool = False
    mixed_q2_k: bool = False
    mixed_j32_rows: tuple[int, int] = (0, 0)
    full_i: bool = False
    full_j: bool = False

    def __post_init__(self) -> None:
        rows_a, rows_b = self.mixed_j32_rows
        if self.mixed_j32_tails:
            if (
                self.kind != ForwardKind.GROUPED_SERIAL
                or self.j != 64
                or self.nrows_weight != 2048
                or self.blocks_per_weight_row != 2
            ):
                raise ValueError("mixed J32 tails require the grouped J64 K512 shape")
            if self.quant_type not in {QuantType.Q4_K, QuantType.IQ2_S}:
                raise ValueError("mixed J32 tails require Q4_K or IQ2_S")
            if (rows_a == 0) != (rows_b == 0):
                raise ValueError("mixed J32 row bounds must both be zero or positive")
            if rows_a < 0 or rows_b < 0 or (rows_a > 0 and rows_a >= rows_b):
                raise ValueError("mixed J32 row bounds must be ordered distinct values")
            if self.quant_type == QuantType.Q4_K and self.mixed_j32_rows == (0, 0):
                raise ValueError("Q4_K mixed J32 tails require bounded aggregate rows")
            if self.quant_type == QuantType.IQ2_S and self.mixed_j32_rows != (0, 0):
                raise ValueError("IQ2_S mixed J32 tails do not accept aggregate bounds")
        elif self.mixed_j32_rows != (0, 0):
            raise ValueError("mixed J32 row bounds require mixed J32 tails")


@dataclass(frozen=True)
class DenseBackwardConfig:
    quant_type: QuantType
    n_tiles: int
    k_iteration: int
    group_m: int
    m_tiles_per_wave: int
    decoder_width: int
    prefetch_local: bool
    full_tiles: bool
    prefetch_packed: bool
    lds_padding: int
    vector_local_load: bool
    lds_swizzle_chunk: int
    pack_q5_quant_bytes: bool
    pack_q6_quant_bytes: bool
    exact_out_features: int = 0
    exact_in_features: int = 0
    active_waves: int = 4


@dataclass(frozen=True)
class GroupedBackwardConfig:
    kind: GroupedBackwardKind
    quant_type: QuantType | None = None
    n_tiles: int = 0
    m_tiles_per_wave: int = 0
    reduction_unroll: int = 0

    def __post_init__(self) -> None:
        tuned_kinds = {
            GroupedBackwardKind.TUNED_DEEPSEEK_PAIR,
            GroupedBackwardKind.TUNED_FIXED_Q8_0,
        }
        geometry = (self.n_tiles, self.m_tiles_per_wave, self.reduction_unroll)
        if self.kind not in tuned_kinds:
            if geometry != (0, 0, 0):
                raise ValueError("grouped backward geometry requires a tuned kind")
            return
        if self.kind == GroupedBackwardKind.TUNED_DEEPSEEK_PAIR:
            if self.quant_type != QuantType.IQ2_XXS or geometry != (4, 2, 1):
                raise ValueError("qualified DeepSeek pair geometry is IQ2_XXS N4 M2 U1")
        elif self.quant_type is not None or geometry != (4, 3, 1):
            raise ValueError("qualified fixed Q8_0 geometry is N4 M3 U1")


KernelConfig = ForwardConfig | DenseBackwardConfig | GroupedBackwardConfig


_PREAMBLE = """// Generated by tools/build_mmq_bundle.py. Do not edit directly.
#ifdef __HIP_NO_HALF_OPERATORS__
#undef __HIP_NO_HALF_OPERATORS__
#endif
#ifdef __HIP_NO_HALF_CONVERSIONS__
#undef __HIP_NO_HALF_CONVERSIONS__
#endif

"""


def _cpp_bool(value: bool) -> str:
    return "true" if value else "false"


def _cpp_quant(quant_type: QuantType | None) -> str:
    if quant_type is None:
        raise ValueError("this kernel kind requires a quant type")
    return f"GGML_TYPE_{quant_type.name}"


def _render_forward(symbol: str, config: ForwardConfig) -> str:
    prefix = _PREAMBLE + '#include "mmq_core.cuh"\n\n'
    mixed_j32_rows = "".join(
        f",\n        {rows}" for rows in config.mixed_j32_rows if rows > 0
    )
    if config.kind == ForwardKind.QUANTIZE:
        quant_type = _cpp_quant(config.quant_type)
        return (
            prefix
            + f"""extern "C" __launch_bounds__(512, 1) __global__
void {symbol}(
        const __hip_bfloat16 * __restrict__ input,
        block_q8_1_mmq * __restrict__ output,
        int64_t rows,
        int64_t rows_padded,
        int64_t k) {{
    quantize_bf16_mmq_q8_1_body<{quant_type}>(
        input, output, rows, rows_padded, k);
}}
"""
        )

    if config.kind == ForwardKind.DENSE:
        quant_type = _cpp_quant(config.quant_type)
        return (
            prefix
            + f"""extern "C" __launch_bounds__(MMQ_NTHREADS, 2) __global__
void {symbol}(
        const char * __restrict__ weights,
        const int * __restrict__ activations,
        __hip_bfloat16 * __restrict__ dst,
        int nrows_weight,
        int nrows_activation,
        int nrows_activation_padded,
        int blocks_per_weight_row) {{
    dense_mmq_bf16_body<
        {quant_type},
        {config.j},
        {config.blocks_per_weight_row},
        {_cpp_bool(config.full_i)},
        {_cpp_bool(config.full_j)}>(
        weights,
        activations,
        dst,
        nrows_weight,
        nrows_activation,
        nrows_activation_padded,
        blocks_per_weight_row);
}}
"""
        )

    if config.kind == ForwardKind.GROUPED_SERIAL:
        quant_type = _cpp_quant(config.quant_type)
        return (
            prefix
            + f"""extern "C" __launch_bounds__(MMQ_NTHREADS, 2) __global__
void {symbol}(
        const char * __restrict__ weights,
        const int * __restrict__ activations,
        __hip_bfloat16 * __restrict__ dst,
        const int64_t * __restrict__ expert_indices,
        const int32_t * __restrict__ expert_offsets,
        int num_experts,
        int nrows_weight,
        int nrows_activation,
        int blocks_per_weight_row,
        int64_t bytes_per_expert) {{
    grouped_mmq_bf16_body<
        {quant_type},
        {config.j},
        {config.nrows_weight},
        {config.blocks_per_weight_row},
        {_cpp_bool(config.mixed_j32_tails)},
        {_cpp_bool(config.mixed_q2_k)},
        {_cpp_bool(config.rolled_q2)}{mixed_j32_rows}>(
            weights,
            activations,
            dst,
            expert_indices,
            expert_offsets,
            num_experts,
            nrows_weight,
            nrows_activation,
            blocks_per_weight_row,
            bytes_per_expert);
}}
"""
        )

    if config.kind == ForwardKind.GROUPED_ROW_TASK:
        quant_type = _cpp_quant(config.quant_type)
        return (
            prefix
            + f"""extern "C" __launch_bounds__(MMQ_NTHREADS, 2) __global__
void {symbol}(
        const char * __restrict__ weights,
        const int * __restrict__ activations,
        __hip_bfloat16 * __restrict__ dst,
        const int32_t * __restrict__ task_count,
        const int32_t * __restrict__ task_experts,
        const int32_t * __restrict__ task_row_starts,
        const int32_t * __restrict__ task_row_ends,
        int nrows_activation,
        int64_t bytes_per_expert) {{
    grouped_mmq_row_task_body<
        {quant_type},
        {config.j},
        {config.nrows_weight},
        {config.blocks_per_weight_row}>(
            weights,
            activations,
            dst,
            task_count,
            task_experts,
            task_row_starts,
            task_row_ends,
            nrows_activation,
            bytes_per_expert);
}}
"""
        )

    if config.kind == ForwardKind.FIXED_GROUPED:
        return (
            prefix
            + f"""extern "C" __launch_bounds__(MMQ_NTHREADS, 2) __global__
void {symbol}(
        const char * __restrict__ weights,
        const int * __restrict__ activations,
        __hip_bfloat16 * __restrict__ dst,
        int tokens,
        int nrows_weight,
        int64_t bytes_per_group) {{
    fixed_grouped_q8_0_mmq_bf16_body<
        {config.j},
        {config.groups},
        {config.blocks_per_weight_row},
        {_cpp_bool(config.fallback)}>(
            weights,
            activations,
            dst,
            tokens,
            nrows_weight,
            bytes_per_group);
}}
"""
        )

    if config.kind == ForwardKind.ROW_TASK_SETUP:
        return (
            prefix
            + f"""extern "C" __launch_bounds__(256, 1) __global__
void {symbol}(
        const int64_t * __restrict__ expert_indices,
        const int32_t * __restrict__ expert_offsets,
        int32_t * __restrict__ task_count,
        int32_t * __restrict__ task_experts,
        int32_t * __restrict__ task_row_starts,
        int32_t * __restrict__ task_row_ends,
        int num_experts,
        int num_groups,
        int nrows_activation,
        int row_tile) {{
    grouped_mmq_build_row_tasks_body(
        expert_indices,
        expert_offsets,
        task_count,
        task_experts,
        task_row_starts,
        task_row_ends,
        num_experts,
        num_groups,
        nrows_activation,
        row_tile);
}}
"""
        )

    raise ValueError(f"unsupported forward kind {config.kind}")


def _render_dense_backward(symbol: str, config: DenseBackwardConfig) -> str:
    return (
        _PREAMBLE
        + f"""#include "ck/mmq_backward.cuh"

extern "C" __launch_bounds__(torch_ggml_ops::ck::BACKWARD_THREADS, 2) __global__
void {symbol}(
        const __hip_bfloat16 * __restrict__ grad_output,
        const char * __restrict__ packed_weight,
        __hip_bfloat16 * __restrict__ grad_input,
        int rows,
        int out_features,
        int in_features,
        int blocks_per_weight_row) {{
    torch_ggml_ops::ck::dense_mmq_grad_input_body<
        {_cpp_quant(config.quant_type)},
        {config.exact_out_features},
        {config.exact_in_features},
        {config.n_tiles},
        {config.k_iteration},
        {config.group_m},
        {config.m_tiles_per_wave},
        {config.active_waves},
        {config.decoder_width},
        {_cpp_bool(config.prefetch_local)},
        {_cpp_bool(config.full_tiles)},
        {_cpp_bool(config.prefetch_packed)},
        {config.lds_padding},
        {_cpp_bool(config.vector_local_load)},
        {config.lds_swizzle_chunk},
        {_cpp_bool(config.pack_q5_quant_bytes)},
        {_cpp_bool(config.pack_q6_quant_bytes)}>(
            grad_output,
            packed_weight,
            grad_input,
            rows,
            out_features,
            in_features,
            blocks_per_weight_row);
}}
"""
    )


_SINGLE_ARGUMENTS = """        const __hip_bfloat16 * __restrict__ grad_output,
        const char * __restrict__ packed_weight,
        __hip_bfloat16 * __restrict__ grad_input,
        const int64_t * __restrict__ expert_indices,
        const int32_t * __restrict__ expert_offsets,
        int num_experts,
        int rows,
        int64_t bytes_per_expert"""

_SINGLE_VALUES = """        grad_output,
        packed_weight,
        grad_input,
        expert_indices,
        expert_offsets,
        num_experts,
        rows,
        bytes_per_expert"""

_PAIR_ARGUMENTS = """        const __hip_bfloat16 * __restrict__ first_grad_output,
        const __hip_bfloat16 * __restrict__ second_grad_output,
        const char * __restrict__ first_packed_weight,
        const char * __restrict__ second_packed_weight,
        __hip_bfloat16 * __restrict__ grad_input,
        const int64_t * __restrict__ expert_indices,
        const int32_t * __restrict__ expert_offsets,
        int num_experts,
        int rows,
        int64_t bytes_per_expert"""

_PAIR_VALUES = """        first_grad_output,
        second_grad_output,
        first_packed_weight,
        second_packed_weight,
        grad_input,
        expert_indices,
        expert_offsets,
        num_experts,
        rows,
        bytes_per_expert"""

_ROW_TASK_ARGUMENTS = """        const __hip_bfloat16 * __restrict__ grad_output,
        const char * __restrict__ packed_weight,
        __hip_bfloat16 * __restrict__ grad_input,
        const int32_t * __restrict__ task_count,
        const int32_t * __restrict__ task_experts,
        const int32_t * __restrict__ task_row_starts,
        const int32_t * __restrict__ task_row_ends,
        int64_t bytes_per_expert"""

_ROW_TASK_VALUES = """        grad_output,
        packed_weight,
        grad_input,
        task_count,
        task_experts,
        task_row_starts,
        task_row_ends,
        bytes_per_expert"""

_FIXED_ARGUMENTS = """        const __hip_bfloat16 * __restrict__ grad_output,
        const char * __restrict__ packed_weight,
        __hip_bfloat16 * __restrict__ grad_input,
        int tokens,
        int out_features,
        int64_t bytes_per_group"""


_SPECIAL_GROUPED_CALLS = {
    GroupedBackwardKind.Q4_SINGLE_M64: "torch_ggml_ops::ck::grouped_mmq_grad_input_q4_small_body",
    GroupedBackwardKind.Q4_SINGLE_M128: "torch_ggml_ops::ck::grouped_mmq_grad_input_q4_small_s2_body",
    GroupedBackwardKind.Q3_PAIR_M64: "torch_ggml_ops::ck::grouped_mmq_pair_grad_input_q3_small_body",
    GroupedBackwardKind.Q3_PAIR_M128: "torch_ggml_ops::ck::grouped_mmq_pair_grad_input_q3_n64_large_body",
    GroupedBackwardKind.Q5_SINGLE_M64: "torch_ggml_ops::ck::grouped_mmq_grad_input_q5_small_body",
    GroupedBackwardKind.IQ2_S_SINGLE_M64: "torch_ggml_ops::ck::grouped_mmq_grad_input_iq2_tiled_body<true>",
    GroupedBackwardKind.IQ2_S_SINGLE_M128: "torch_ggml_ops::ck::grouped_mmq_grad_input_iq2_s2_body",
    GroupedBackwardKind.IQ2_S_PAIR_M64: "torch_ggml_ops::ck::grouped_mmq_pair_grad_input_iq2_tiled_body<true>",
    GroupedBackwardKind.IQ2_S_PAIR_M128: "torch_ggml_ops::ck::grouped_mmq_pair_grad_input_iq2_n64_large_body",
    GroupedBackwardKind.Q4_ROW_TASK: "torch_ggml_ops::ck::grouped_mmq_grad_input_q4_row_task_body",
    GroupedBackwardKind.Q5_ROW_TASK: "torch_ggml_ops::ck::grouped_mmq_grad_input_q5_row_task_body",
    GroupedBackwardKind.IQ2_S_ROW_TASK: "torch_ggml_ops::ck::grouped_mmq_grad_input_iq2_row_task_body",
    GroupedBackwardKind.Q2_K_SINGLE_M64_U1: "torch_ggml_ops::ck::grouped_mmq_grad_input_deepseek_body<"
    "GGML_TYPE_Q2_K, 4096, 2048, 8, 1, 1, true>",
    GroupedBackwardKind.Q2_K_SINGLE_M128_U1: "torch_ggml_ops::ck::grouped_mmq_grad_input_deepseek_body<"
    "GGML_TYPE_Q2_K, 4096, 2048, 8, 2, 1, true>",
    GroupedBackwardKind.IQ2_XXS_PAIR_M64: "torch_ggml_ops::ck::grouped_mmq_pair_grad_input_deepseek_body<"
    "GGML_TYPE_IQ2_XXS, 2048, 4096, 16, 1, true>",
    GroupedBackwardKind.Q2_K_SINGLE_M128_U2: "torch_ggml_ops::ck::grouped_mmq_grad_input_deepseek_body<"
    "GGML_TYPE_Q2_K, 4096, 2048, 8, 2, 2, true>",
}

_PAIR_KINDS = {
    GroupedBackwardKind.Q3_PAIR_M64,
    GroupedBackwardKind.Q3_PAIR_M128,
    GroupedBackwardKind.IQ2_S_PAIR_M64,
    GroupedBackwardKind.IQ2_S_PAIR_M128,
    GroupedBackwardKind.IQ2_XXS_PAIR_M64,
}

_ROW_TASK_KINDS = {
    GroupedBackwardKind.Q4_ROW_TASK,
    GroupedBackwardKind.Q5_ROW_TASK,
    GroupedBackwardKind.IQ2_S_ROW_TASK,
}


def _grouped_entry(symbol: str, arguments: str, values: str, call: str) -> str:
    return f"""extern "C" __launch_bounds__(torch_ggml_ops::ck::BACKWARD_THREADS, 2) __global__
void {symbol}(
{arguments}) {{
    {call}(
{values});
}}
"""


def _render_grouped_backward(symbol: str, config: GroupedBackwardConfig) -> str:
    prefix = _PREAMBLE + '#include "ck/grouped_mmq_backward.cuh"\n\n'
    kind = config.kind
    if kind == GroupedBackwardKind.GENERIC_SINGLE:
        quant_type = _cpp_quant(config.quant_type)
        return (
            prefix
            + f"""extern "C" __launch_bounds__(torch_ggml_ops::ck::GROUPED_BACKWARD_THREADS, 1) __global__
void {symbol}(
        const __hip_bfloat16 * __restrict__ grad_output,
        const char * __restrict__ packed_weight,
        __hip_bfloat16 * __restrict__ grad_input,
        const int64_t * __restrict__ expert_indices,
        const int32_t * __restrict__ expert_offsets,
        int num_experts,
        int rows,
        int out_features,
        int in_features,
        int blocks_per_weight_row,
        int64_t bytes_per_expert) {{
    torch_ggml_ops::ck::grouped_mmq_grad_input_body<{quant_type}>(
        grad_output,
        packed_weight,
        grad_input,
        expert_indices,
        expert_offsets,
        num_experts,
        rows,
        out_features,
        in_features,
        blocks_per_weight_row,
        bytes_per_expert);
}}
"""
        )

    if kind == GroupedBackwardKind.GENERIC_PAIR:
        quant_type = _cpp_quant(config.quant_type)
        return (
            prefix
            + f"""extern "C" __launch_bounds__(torch_ggml_ops::ck::GROUPED_BACKWARD_THREADS, 1) __global__
void {symbol}(
        const __hip_bfloat16 * __restrict__ first_grad_output,
        const __hip_bfloat16 * __restrict__ second_grad_output,
        const char * __restrict__ first_packed_weight,
        const char * __restrict__ second_packed_weight,
        __hip_bfloat16 * __restrict__ grad_input,
        const int64_t * __restrict__ expert_indices,
        const int32_t * __restrict__ expert_offsets,
        int num_experts,
        int rows,
        int out_features,
        int in_features,
        int blocks_per_weight_row,
        int64_t bytes_per_expert) {{
    torch_ggml_ops::ck::grouped_mmq_pair_grad_input_body<{quant_type}>(
        first_grad_output,
        second_grad_output,
        first_packed_weight,
        second_packed_weight,
        grad_input,
        expert_indices,
        expert_offsets,
        num_experts,
        rows,
        out_features,
        in_features,
        blocks_per_weight_row,
        bytes_per_expert);
}}
"""
        )

    if kind == GroupedBackwardKind.FIXED_Q8_0_GENERIC:
        return (
            prefix
            + f"""extern "C" __launch_bounds__(torch_ggml_ops::ck::GROUPED_BACKWARD_THREADS, 1) __global__
void {symbol}(
{_FIXED_ARGUMENTS}) {{
    torch_ggml_ops::ck::fixed_grouped_q8_0_grad_input_body(
        grad_output,
        packed_weight,
        grad_input,
        tokens,
        out_features,
        bytes_per_group);
}}
"""
        )

    if kind == GroupedBackwardKind.FIXED_Q8_0_M256:
        return (
            prefix
            + f"""extern "C" __launch_bounds__(torch_ggml_ops::ck::BACKWARD_THREADS, 1) __global__
void {symbol}(
{_FIXED_ARGUMENTS}) {{
    torch_ggml_ops::ck::fixed_grouped_q8_0_grad_input_tiled_body<4, 16, 0>(
        grad_output,
        packed_weight,
        grad_input,
        tokens,
        bytes_per_group);
}}
"""
        )

    if kind == GroupedBackwardKind.TUNED_FIXED_Q8_0:
        return (
            prefix
            + f"""extern "C" __launch_bounds__(torch_ggml_ops::ck::BACKWARD_THREADS, 2) __global__
void {symbol}(
{_FIXED_ARGUMENTS}) {{
    torch_ggml_ops::ck::fixed_grouped_q8_0_grad_input_tiled_body<
        {config.m_tiles_per_wave}, 16, 0>(
        grad_output,
        packed_weight,
        grad_input,
        tokens,
        bytes_per_group);
}}
"""
        )

    if kind == GroupedBackwardKind.TUNED_DEEPSEEK_PAIR:
        return prefix + _grouped_entry(
            symbol,
            _PAIR_ARGUMENTS,
            _PAIR_VALUES,
            "torch_ggml_ops::ck::grouped_mmq_pair_grad_input_deepseek_body<"
            f"GGML_TYPE_IQ2_XXS, 2048, 4096, 16, {config.m_tiles_per_wave}, true>",
        )

    call = _SPECIAL_GROUPED_CALLS.get(kind)
    if call is None:
        raise ValueError(f"unsupported grouped backward kind {kind}")
    if kind in _PAIR_KINDS:
        return prefix + _grouped_entry(symbol, _PAIR_ARGUMENTS, _PAIR_VALUES, call)
    if kind in _ROW_TASK_KINDS:
        return prefix + _grouped_entry(
            symbol, _ROW_TASK_ARGUMENTS, _ROW_TASK_VALUES, call
        )
    return prefix + _grouped_entry(symbol, _SINGLE_ARGUMENTS, _SINGLE_VALUES, call)


def render_wrapper(symbol: str, config: KernelConfig) -> str:
    """Return one concrete source file with no build-selector macros."""
    if isinstance(config, ForwardConfig):
        return _render_forward(symbol, config)
    if isinstance(config, DenseBackwardConfig):
        return _render_dense_backward(symbol, config)
    if isinstance(config, GroupedBackwardConfig):
        return _render_grouped_backward(symbol, config)
    raise TypeError(f"unsupported MMQ kernel config {type(config).__name__}")
